name: desafio_rick_and_morty
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  graphql_flutter: ^5.1.0
  google_fonts: ^3.0.1
  cached_network_image: ^3.2.1
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.9.0"

flutter_icons:
    image_path: "assets/icon/icons8-morty-smith-100.png"
    android: true
    ios: true

flutter:
    uses-material-design: true
